### ISSUE TITLE
Segmentation Fault when `read_to_end`

### ISSUE THREAD

**Issue by DyeKuu** [alexcrichton/ssh2-rs#195]
I got the SegFault when running the `read_to_end` in the codes below.

```rust
let mut sftp_file :ssh2::File = stocks_file.sftp_open()?;
let mut buffer: Vec<u8> = Vec::new();
use std::io::*;
BufReader::with_capacity(1 << 16, sftp_file).read_to_end(&mut buffer)?;
```

```
Thread 1 "integrations_cd" received signal SIGSEGV, Segmentation fault.
sftp_read (buffer_size=65536, buffer=0x555555e289c0 "", handle=0x555555d93360) at libssh2/src/sftp.c:1342
1342        LIBSSH2_SESSION *session = channel->session;
(gdb) bt
#0  sftp_read (buffer_size=65536, buffer=0x555555e289c0 "", handle=0x555555d93360) at libssh2/src/sftp.c:1342
#1  libssh2_sftp_read (hnd=0x555555d93360, buffer=0x555555e289c0 "", buffer_maxlen=65536) at libssh2/src/sftp.c:1738
#2  0x000055555568f0db in <ssh2::sftp::File as std::io::Read>::read () at /home/kunhao/.cargo/registry/src/github.com-1ecc6299db9ec823/ssh2-0.8.0/src/sftp.rs:578
#3  0x000055555561110b in <std::io::buffered::BufReader<R> as std::io::BufRead>::fill_buf () at /home/kunhao/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/buffered.rs:314
#4  <std::io::buffered::BufReader<R> as std::io::Read>::read () at /home/kunhao/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/buffered.rs:274
#5  0x0000555555636c2c in std::io::read_to_end_with_reservation () at /home/kunhao/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/mod.rs:396
#6  std::io::read_to_end () at /home/kunhao/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/mod.rs:363
#7  0x000055555560dea1 in std::io::Read::read_to_end () at /home/kunhao/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/mod.rs:680
```

**Comment by Ten0** [comment]
Because the drop impls are broken everywhere.
Here: https://github.com/alexcrichton/ssh2-rs/commit/756a61d0271402ec642d6fdb866fbb92e2d4a876#diff-c265dd0c753a70df9eb445c98de4fb74
And here: https://github.com/alexcrichton/ssh2-rs/commit/ebea1cce2a4c550ad11dbf10c20ab2379a37a0e2#diff-c265dd0c753a70df9eb445c98de4fb74
