### ISSUE TITLE
userauth_pubkey_file fails on Windows

### ISSUE THREAD

**Issue by jsurkont** [alexcrichton/ssh2-rs#221]
Pubkey authenticaiton works as expected on Linux. However, when running on Windows, `userauth_pubkey_file` fails with `Error { code: Session(-1), msg: "unknown error" }` (I'm using the same key on both systems). I can successfully connect using `userauth_password`, so I can exclude networking issues. 

Here is a minimal example:

```rust
use ssh2::Session;
use std::net::TcpStream;
use std::path::Path;

fn main() {
    let host = "10.0.2.2:2221";
    let username = "foo";
    let key_path = Path::new("C:\\Users\\bar\\Documents\\id_rsa_test");
    let password = Some("password");
    assert!(key_path.exists());
    let tcp = TcpStream::connect(host).unwrap();
    let mut session = Session::new().unwrap();
    session.set_tcp_stream(tcp);
    session.handshake().unwrap();
    session.userauth_pubkey_file(username, None, key_path, password).unwrap();
}
```

I checked local variables in `userauth_pubkey_file` and the values seem to be correct

```
Private key "C:/Users/bar/Documents/id_rsa_test"
Username "foo"
Passphrase Some("password")
```

Am I missing something Windows specific? Or the problem is with `userauth_pubkey_file` implementation for Windows?

**Comment by 0x4ndy** [comment]
I'm having exactly the same issue in in 0.9.3. How was this fixed?

Code:
```
use ssh2::Session;
use std::net::TcpStream;
use std::path::Path;

fn main() {
    let host = "10.10.1.100:22";
    let username = "user";
    let key_path = Path::new("C:/andy/tmp/id_rsa");
    assert!(key_path.exists());
    let tcp = TcpStream::connect(host).unwrap();
    let mut session = Session::new().unwrap();
    session.set_tcp_stream(tcp);
    session.handshake().unwrap();
    session.userauth_pubkey_file(username, None, key_path, None).unwrap();
}
```

Backtrace:
```
PS C:\andy\dev\sshtest> cargo run
   Compiling sshtest v0.1.0 (C:\andy\dev\sshtest)
    Finished dev [unoptimized + debuginfo] target(s) in 4.63s
     Running `target\debug\sshtest.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Session(-1), msg: "unknown error" }', src\main.rs:14:66
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\panicking.rs:100
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\result.rs:1616
   3: enum$<core::result::Result<tuple$<>,ssh2::error::Error>, 0, 1, Err>::unwrap<tuple$<>,ssh2::error::Error>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\result.rs:1298
   4: sshtest::main
             at .\src\main.rs:14
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\sshtest.exe` (exit code: 101)
```

**Comment by jsurkont** [comment]
@0x4ndy I just tried my example again and I don't get an error with ssh2-rs 0.9.3 (and libssh2-sys v0.2.23). One thing that might be important is that I set some features in `cargo.toml`

```toml
[dependencies]
ssh2 = {version = "0.9", features = ["vendored-openssl", "openssl-on-win32"]}
```
Maybe that would help?

**Comment by 0x4ndy** [comment]
@jsurkont thanks for the hint, but no luck. I get the following:
```
error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by:
  process didn't exit successfully: `C:\andy\dev\sshtest\target\debug\build\openssl-sys-24e9c6e3f9f60a7f\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\andy\\dev\\sshtest\\target\\debug\\build\\openssl-sys-43d0834973631a00\\out\\openssl-build\\install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"
```

I'm just trying to run the above example so my Cargo.toml has just one dependency:
```
[dependencies]
ssh2 = {version = "0.9", features = ["vendored-openssl", "openssl-on-win32"]}
```

What else can I be missing?

**Comment by 0x4ndy** [comment]
@jsurkont actually I just managed to make it work on the other Windows environment I have, so there's definitely some ssl stuff I'm missing. Anyway, thanks for help!

**Comment by jsurkont** [comment]
@0x4ndy you're welcome! One dependency that you might be missing in your first environment could be Perl (it seems to be required for building `openssl-sys`). I have `strawberryperl` installed in my env.

**Comment by 0x4ndy** [comment]
@jsurkont yes, I've installed that too. But Perl in the end still complained that it's a wrong platform (although I have the windows portable zip). I don't have admin rights to this box and I'm trying to workout things around.

**Comment by jsurkont** [comment]
@0x4ndy it indeed looks that the problem is the Perl installation (I only tested with Perl installed using the admin user). Windows is not my primary platform, so unfortunately I don't have good suggestions for fixing the issue.

**Comment by yodaldevoid** [comment]
@0x4ndy If you have a test case that you can share (better yet if if has been minified), please do share it in a new issue.

**Comment by giftig** [comment]
I'm having the same `Session(-1): unknown error` issue, and it's quite difficult to debug as the error is very opaque. Unfortunately I'm quite new to Rust as well so I'm not sure how to debug this further.

My scenario is very similar to the above but I'm using `ssh2-rs 0.9.4` so I should have the fix. What was the fix for the issue which went into 0.9.3?

I'm building on linux, and the executable works fine when also running on linux. I'm trying to build for windows via `cargo build --target x86_64-pc-windows-gnu` but when running on windows I'm encountering this error. I'm using `userauth_pubkey_file` as described in the issue.

Since `vendored-openssl` was mentioned above I also tried this, but the result was the same; works fine on linux but not on windows.

**Comment by xeekst** [comment]
> @0x4ndy I just tried my example again and I don't get an error with ssh2-rs 0.9.3 (and libssh2-sys v0.2.23). One thing that might be important is that I set some features in `cargo.toml`
> 
> ```toml
> [dependencies]
> ssh2 = {version = "0.9", features = ["vendored-openssl", "openssl-on-win32"]}
> ```
> 
> Maybe that would help?

when I config these features, it works. thanks.
