### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "transport read" }'

### ISSUE THREAD

**Issue by ivan-hz** [alexcrichton/ssh2-rs#283]
I ran the code with the following error, and found that the device received the command when "$env: RUST_BACKTRACE=1;" was not added. But the code reports an error

Describe the bug
```
C:\rust\shell>cargo run
thread 'main' panicked at 'called on an value: Custom { kind: Other, error: "transport read" }', src\main.rs:18:36
note: run with environment variable to display a backtraceResult::unwrap()ErrRUST_BACKTRACE=1

C:\rust\shell> $env:RUST_BACKTRACE=1 ; cargo run
thread 'main' panicked at 'called on an value: Error { code: Session(-8), msg: "Unable to exchange encryption keys" }', src\main.rs:11:22
stack backtrace:
0: rust_begin_unwind
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src/panicking.rs:575:5
1: core::panicking::panic_fmt
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src/panicking.rs:65:14
2: core::result::unwrap_failed
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src/result.rs:1791:5
3: core::result::Result<T,E>::unwrap
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\core\src/result.rs:1113:23
4: shell::main
at .\src\main.rs:11:5
5: core::ops::function::FnOnce::call_once
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\core\src\ops/function.rs:251:5
note: Some details are omitted, run with for a verbose backtrace.
error: process didn't exit successfully: (exit code: 101)Result::unwrap()ErrRUST_BACKTRACE=fulltarget\debug\shell.exe
```

To Reproduce
```
use std::net::TcpStream;
use ssh2::Session;
use std::io::prelude::*;

fn main() {
    let tcp = TcpStream::connect("xxxx:22").unwrap();
    let mut sess = Session::new().unwrap();
    sess.set_tcp_stream(tcp);
    sess.handshake().unwrap();

    sess.userauth_password("xxxx","xxx").unwrap();

    let mut channel = sess.channel_session().unwrap();
    channel.exec("show ip int brie").unwrap();
    let mut s = String::new();
    channel.read_to_string(&mut s).unwrap();
    println!("{}",s);
    channel.wait_close();
}
```

Expected behavior
Please help to see how to solve this problem，I'm a beginner. I'm trying to make an interactive web ssh

**Comment by yodaldevoid** [comment]
It was a little hard to figure out what was actually failing since I think the code you provided has different line numbers to what you ran. You've got two different errors here. The first panic is when you call `channel.read_to_string(&mut s).unwrap()`. The second one (the one with backtrace enabled) is from when you call `sess.handshake().unwrap()`.

I am not sure these errors are your fault. I have a feeling that something went wrong on the server side that cut you off. I'd suggest calling `Session::trace` early on into your program with at the very least `TraceFlags::CONN` enabled and see what you can figure out from the debug messages. I honestly can't give any more guidance than that.
