### ISSUE TITLE
Ssh2 library not supporting Kex ecdh-sha2-nistp384 

### ISSUE THREAD

**Issue by Manikanth952** [alexcrichton/ssh2-rs#332]
With SSH2, Kex ecdh-sha2-nistp384 is not being supported.
We tried enabling this key algorithm using macro to enable libssh2_ecdsa. Still its not working.
This Kex support is highly needed from SSH2 crate. If this is a bug, please provide and update with fix.
If its intentionally not supported, it would be great if you can provide the support.
We tried exploring Russh crate, but its totally a different crate as it is completely async and also upload file using this crate is taking huge time as it writes to a buffer.

It would be great if we can get the support in SSH2 crate.

**Comment by yodaldevoid** [comment]
This may have been fixed with #334. Please let me know if you need anything else beyond that.

**Comment by Manikanth952** [comment]
> This may have been fixed with #334. Please let me know if you need anything else beyond that.

Thanks for the reply @yodaldevoid .
I tried pulling this libssh2 fix locally and provided this path in toml. Still i see sam error and below are the only supported kex list.

Ok(["diffie-hellman-group-exchange-sha256", "diffie-hellman-group16-sha512", "diffie-hellman-group18-sha512", "diffie-hellman-group14-sha256", "diffie-hellman-group14-sha1", "diffie-hellman-group1-sha1", "diffie-hellman-group-exchange-sha1", "ext-info-c", "kex-strict-c-v00@openssh.com"])
[2024-11-05T20:41:43Z ERROR rscm_Conn] SSH handshake failed: Error { code: Session(-5), msg: "Unable to exchange encryption keys" }
Error: Error { code: Session(-5), msg: "Unable to exchange encryption keys" }

Also any reason why this is not released as a proper version upgrade for ssh2?. If you can mainline changes as a version release , in runtime changes will take care

**Comment by atulkhare4096** [comment]
@yodaldevoid Note that the issue is specific to Windows. It appears to work without problems on Linux with version 0.9.4. Perhaps, this has something to do with the build options used on Windows for the libssh2-sys crate?

**Comment by Manikanth952** [comment]
@yodaldevoid , on Windows libssh2-sys crate is using wincng instead of openssl.

      if target.contains("windows") {
              cfg.include("libssh2/win32");
              cfg.define("LIBSSH2_WIN32", None);
              cfg.file("libssh2/src/agent_win.c");
      
              if env::var_os("CARGO_FEATURE_OPENSSL_ON_WIN32").is_some() {
                  cfg.define("LIBSSH2_OPENSSL", None);
                  cfg.define("HAVE_EVP_AES_128_CTR", None);
                  cfg.file("libssh2/src/openssl.c");
                  println!("cargo:rustc-link-lib=static=libssl");
                  println!("cargo:rustc-link-lib=static=libcrypto");
              } **else {
                  cfg.define("LIBSSH2_WINCNG", None);**
                  cfg.file("libssh2/src/wincng.c");
              }

we tried downloading openssl and setting env variable but we are facing build compilation issues. I tried manually to run and install make file using nmake but still unable to build with openssl. Do we have any specific requirements and procedure to build with openssl on windows?. 
Also there seems to be a bug on wincng for not supporting kex ecdh-sha2-nistp384.

Any fix on either building with openssl or wincng will unblock the issue.

**Comment by yylime** [comment]
> This may have been fixed with #334. Please let me know if you need anything else beyond that.这可能已通过 #334 修复。除此之外，如果您还需要其他任何信息，请告诉我。

When I used ssh2 = "0.9.0" to connect to my switch, which only supports the **diffie-hellman-group1-sha**1 key exchange algorithm, I encountered an error. 

`    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/switch_ssh`
thread 'main' panicked at src/main.rs:13:22:
called `Result::unwrap()` on an `Err` value: Error { code: Session(-41), msg: "out of bounds" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1104:23
   4: switch_ssh::main
             at ./src/main.rs:13:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.` 

However, when I changed the ssh2 version to 0.8, it worked for this switch, but I then faced the following error when connecting to a newer switch:`SSH handshake failed: Error { code: Session(-5), msg: "Unable to exchange encryption keys" }`
What should I do to resolve this issue?

**Comment by yodaldevoid** [comment]
Building with `openssl` on Windows should work as long as you use the `openssl-on-win32` feature of `ssh2`. It may be simplest to also use the `vendored-openssl` feature, though it isn't technically required.

**Comment by duhbbx** [comment]
https://github.com/libssh2/libssh2/blob/a312b43325e3383c865a87bb1d26cb52e3292641/src/wincng.h


```c
/*
 * Conditionally enable ECDSA support.
 *
 * ECDSA support requires the use of
 *
 *   BCryptDeriveKey(..., BCRYPT_KDF_RAW_SECRET, ... )
 *
 * This functionality is only available as of Windows 10. To maintain
 * backward compatibility, ECDSA support is therefore disabled
 * by default and needs to be explicitly enabled using a build
 * flag.
 */
#ifdef LIBSSH2_ECDSA_WINCNG
#define LIBSSH2_ECDSA 1
#else
#define LIBSSH2_ECDSA 0
#endif
```


```c
static const LIBSSH2_KEX_METHOD *libssh2_kex_methods[] = {
#if LIBSSH2_ED25519
    &kex_method_ssh_curve25519_sha256,
    &kex_method_ssh_curve25519_sha256_libssh,
#endif
#if LIBSSH2_ECDSA
    &kex_method_ecdh_sha2_nistp256,
    &kex_method_ecdh_sha2_nistp384,
    &kex_method_ecdh_sha2_nistp521,
#endif
    &kex_method_diffie_helman_group_exchange_sha256,
    &kex_method_diffie_helman_group16_sha512,
    &kex_method_diffie_helman_group18_sha512,
    &kex_method_diffie_helman_group14_sha256,
    &kex_method_diffie_helman_group14_sha1,
    &kex_method_diffie_helman_group1_sha1,
    &kex_method_diffie_helman_group_exchange_sha1,
    &kex_method_extension_negotiation,
    &kex_method_strict_client_extension,
    NULL
};
```

I guess that the macro LIBSSH2_ECDSA_WINCNG was not defined when ssh2 rs was built, which resulted in kex not having a corresponding encryption method.

**Comment by atulkhare4096** [comment]
Thanks @duhbbx. It sounds like this requires a recompilation and a version release of the crate, right?
