### ISSUE TITLE
How to use the features of the old version in the new version？

### ISSUE THREAD

**Issue by yylime** [alexcrichton/ssh2-rs#339]
When I used ssh2 = "0.9.4" to connect to my switch, which only supports the **diffie-hellman-group1-sha1** key exchange algorithm and **ssh-rsa** cipher, I encountered an error.

`   Finisheddevprofile [unoptimized + debuginfo] target(s) in 0.06s Runningtarget/debug/switch_sshthread 'main' panicked at src/main.rs:13:22: calledResult::unwrap()on anErrvalue: Error { code: Session(-41), msg: "out of bounds" } 
stack backtrace: 0: rust_begin_unwind at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5 1: core::panicking::panic_fmt at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14 2: core::result::unwrap_failed at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5 3: core::result::Result<T,E>::unwrap at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1104:23 4: switch_ssh::main at ./src/main.rs:13:5 5: core::ops::function::FnOnce::call_once at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250:5 note: Some details are omitted, run withRUST_BACKTRACE=full for a verbose backtrace.`

However, when I changed the ssh2 version to 0.8, it worked for this switch, but I then faced the following error when connecting to a newer switch:SSH handshake failed: Error { code: Session(-5), msg: "Unable to exchange encryption keys" }
What should I do to resolve this issue?

**Comment by yodaldevoid** [comment]
I believe your issue is with the underlying `libssh2`. You can choose to use a version of `libssh2` that is not the vendored version, but we can't guarantee it will work. You may want to look into the (relatively) recent changes around ssh-rsa support in `libssh2`.

**Comment by yylime** [comment]
> I believe your issue is with the underlying `libssh2`. You can choose to use a version of `libssh2` that is not the vendored version, but we can't guarantee it will work. You may want to look into the (relatively) recent changes around ssh-rsa support in `libssh2`.

omg,  i found it works when i update to ssh2 = "0.9.5", although I don't know what happened. Finally, ssh2 can be used to handle a large number of different types of switches.  Thanks～

**Comment by yodaldevoid** [comment]
I'm glad it worked out for you!
