### ISSUE TITLE
Panic during `Session::scp_send`

### ISSUE THREAD

**Issue by gyscos** [alexcrichton/ssh2-rs#60]
I am getting panics when trying to send a file using this crate:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:           0xe73cec - std::sys::imp::backtrace::tracing::imp::write::hb19afc01d31f8b8d
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:           0xe775ce - std::panicking::default_hook::{{closure}}::hc95fe3ab240055ab
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/panicking.rs:351
   3:           0xe771d4 - std::panicking::default_hook::hb0959de6991e005f
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/panicking.rs:367
   4:           0xe77a6b - std::panicking::rust_panic_with_hook::h2109fde6f0e4c63e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/panicking.rs:555
   5:           0xe778b4 - std::panicking::begin_panic::h49b7a814453fcc40
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/panicking.rs:517
   6:           0xe77829 - std::panicking::begin_panic_fmt::h536a55f472b4abf0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/panicking.rs:501
   7:           0xe777b7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/panicking.rs:477
   8:           0xebff3d - core::panicking::panic_fmt::he66a9a97711f43a8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libcore/panicking.rs:69
   9:           0xebfe74 - core::panicking::panic::h6c850e48e8c19b5e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libcore/panicking.rs:49
  10:           0xbe9efc - <core::option::Option<T>>::unwrap::ha09ee0454bdcc49c
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libcore/macros.rs:21
  11:           0xbf0717 - ssh2::util::SessionBinding::from_raw_opt::h1bf5351e4f3941b8
                        at /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/ssh2-0.3.1/src/util.rs:23
  12:           0xbf020d - ssh2::session::Session::scp_send::h60e18108437c1a5d
                        at /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/ssh2-0.3.1/src/session.rs:462
(the rest of the trace is inside my application)
```

The network conditions on the host _are_ bad, but I wouldn't expect it to lead to panics.

The bug happens semi-regularly, so I can probably provide more information if you need.

Note: I'm linking to musl using [ekidd's docker container](https://github.com/emk/rust-musl-builder) - could it explain this behavior?

EDIT: I also got a panic during `Session::channel_session`, I suspect with the same cause (`Error::last_error` returning `None` in `SessionBinding::from_raw_opt`).

**Comment by alexcrichton** [comment]
I think you're right about what's happening here. A call in libssh2 is returning `NULL` but `Error::last_error` isn't pulling anything out.

This may be a bug in libssh2 under the hood? Reporting an error but forgetting to set a return code? In any case we definitely shouldn't panic here and should probably create a synthetic error indicating "no other error listed"

@gyscos would you be interested in sending a PR for a change like that? If not I can try to take care of it!

**Comment by gyscos** [comment]
Just needs a version bump to publish the fix.

**Comment by alexcrichton** [comment]
Oh sure thing, done now!
