### ISSUE TITLE
0.2.6 fatal: Not a git repository

### ISSUE THREAD

**Issue by WillemMali** [alexcrichton/ssh2-rs#67]
I'm not sure why this issue occurs. I've installed `libssl-dev` and other dependencies. I don't understand what a "not a Git repository" error is doing in a build log.

I was trying to install a new version of Cargo with `cargo install cargo --force`, then I got the same error for `cargo install cargo-update`.

* rustc 1.20.0-nightly (445077963 2017-06-20)
* cargo 0.21.0-nightly (50b1c24d1 2017-06-17)

Log for `cargo install cargo-update`:
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-update v1.1.1
   Compiling void v1.0.2
   Compiling serde v1.0.8
   Compiling percent-encoding v1.0.0
   Compiling regex-syntax v0.4.1
   Compiling embed-resource v1.1.2
   Compiling unicode-normalization v0.1.5
   Compiling gcc v0.3.51
   Compiling array_tool v0.4.0
   Compiling json v0.11.6
   Compiling unicode-segmentation v1.1.0
   Compiling utf8-ranges v1.0.0
   Compiling matches v0.1.6
   Compiling libc v0.2.24
   Compiling ansi_term v0.9.0
   Compiling pkg-config v0.3.9
   Compiling openssl-probe v0.1.1
   Compiling lazy_static v0.2.8
   Compiling strsim v0.6.0
   Compiling bitflags v0.9.1
   Compiling quote v0.3.15
   Compiling semver-parser v0.7.0
   Compiling unicode-width v0.1.4
   Compiling vec_map v0.8.0
   Compiling unicode-xid v0.0.4
   Compiling unreachable v0.1.1
   Compiling cargo-update v1.1.1
   Compiling unicode-bidi v0.3.3
   Compiling thread-id v3.1.0
   Compiling atty v0.2.2
   Compiling memchr v1.0.1
   Compiling rand v0.3.15
   Compiling term_size v0.3.0
   Compiling tabwriter v1.0.3
   Compiling synom v0.11.3
   Compiling thread_local v0.3.3
   Compiling semver v0.6.0
   Compiling textwrap v0.6.0
   Compiling aho-corasick v0.6.3
   Compiling cmake v0.1.24
   Compiling curl-sys v0.3.12
   Compiling openssl-sys v0.9.14
   Compiling libz-sys v1.0.16
   Compiling syn v0.11.11
   Compiling lazysort v0.1.1
   Compiling toml v0.4.1
   Compiling clap v2.25.0
   Compiling idna v0.1.2
   Compiling libgit2-sys v0.6.12
   Compiling libssh2-sys v0.2.6
   Compiling regex v0.2.2
   Compiling url v1.5.0
error: failed to run custom build command for `libssh2-sys v0.2.6`
process didn't exit successfully: `/tmp/cargo-install.gZuO2k8v7E9P/release/build/libssh2-sys-bb7729048b38b82a/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/willem/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.6/libssh2" "-DCRYPTO_BACKEND=OpenSSL" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=/tmp/cargo-install.gZuO2k8v7E9P/release/build/libssh2-sys-79db7a683b1f9e4b/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /home/willem/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.24/src/lib.rs:593
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: cmake::fail
   8: cmake::run
   9: cmake::Config::build
  10: build_script_build::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: <unknown>

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-update v1.1.1`, intermediate artifacts can be found at `/tmp/cargo-install.gZuO2k8v7E9P`

Caused by:
  build failed
```

**Comment by alexcrichton** [comment]
Thanks for the report! The actual error is:

```
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?
```

If you install `cmake` you should be good to go!

**Comment by WillemMali** [comment]
Whoops, thank you for the help!
